title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "© 2026 Aemulus Askar. Все права защищены. Игры и связанные материалы являются интеллектуальной собственностью Aemulus Askar."
