title: "Aemulus Askar"
description: "Official portfolio of a solo game developer. Psychological RPGs, 3D shooters, and projects."

theme: just-the-docs

url: "https://AemulusAskar.github.io"

search_enabled: true

footer_content: "© 2026 Aemulus Askar. All rights reserved. All games, storylines, and related materials are the exclusive intellectual property of the author."
